<#
.SYNOPSIS
  Truncates attendance-related tables and repopulates "Lessons" from lessons.pipe.txt (pipe-delimited).

.PARAMETER Semester
  Value stored in Lessons.Semester (default: Spring2026).

.PARAMETER RoomId
  Default room id for all lessons (default: 1).

.PARAMETER DefaultCredits
  Credits column is not in the CSV; this default is used (default: 3).

.EXAMPLE
  $env:PGPASSWORD = '12345'
  .\Populate-Database.ps1 -HostName localhost -Port 5432 -Database my_ada_attendance_db -UserName postgres

.EXAMPLE (Docker — generate SQL then pipe)
  .\Populate-Database.ps1 -SqlOnly -OutputSqlPath .\seed.sql
  Get-Content .\seed.sql | docker compose exec -T db psql -U postgres -d my_ada_attendance_db
#>
[CmdletBinding(DefaultParameterSetName = 'Params')]
param(
    [Parameter(ParameterSetName = 'Params')]
    [string] $HostName = 'localhost',
    [Parameter(ParameterSetName = 'Params')]
    [int] $Port = 5432,
    [Parameter(ParameterSetName = 'Params')]
    [string] $Database = 'my_ada_attendance_db',
    [Parameter(ParameterSetName = 'Params')]
    [string] $UserName = 'postgres',
    [Parameter(ParameterSetName = 'Params')]
    [string] $Password = $env:PGPASSWORD,
    [Parameter(ParameterSetName = 'Url')]
    [string] $ConnectionUrl,

    [string] $Semester = 'Spring2026',
    [int] $RoomId = 1,
    [int] $DefaultCredits = 3,

    [string] $OutputSqlPath,

    [switch] $SqlOnly,

    [switch] $WhatIf
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Get-PrimaryInstructorKey {
    param([string] $Raw)
    $t = $Raw.Trim()
    if ($t -match '^(?<p>.+?)\(Primary\)') {
        return $matches['p'].Trim()
    }
    return $t
}

function Escape-SqlLiteral {
    param([string] $s)
    if ($null -eq $s) { return '' }
    return $s.Replace("'", "''")
}

$dataPath = Join-Path $PSScriptRoot 'lessons.pipe.txt'
if (-not (Test-Path -LiteralPath $dataPath)) {
    throw "Missing data file: $dataPath"
}

$rows = Import-Csv -LiteralPath $dataPath -Delimiter '|'
if ($rows.Count -lt 1) { throw 'No rows in lessons.pipe.txt' }

$instructorKeys = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
foreach ($r in $rows) {
    [void]$instructorKeys.Add((Get-PrimaryInstructorKey -Raw $r.instructor))
}
$sortedNames = $instructorKeys | Sort-Object
$instructorIdByKey = @{}
$nextId = 1
foreach ($n in $sortedNames) {
    $instructorIdByKey[$n] = $nextId
    $nextId++
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('-- Generated by Populate-Database.ps1')
[void]$sb.AppendLine('BEGIN;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('-- Clear dependent data (matches EF "init" migration; add more tables here if your DB has them)')
[void]$sb.AppendLine('TRUNCATE TABLE')
[void]$sb.AppendLine('  "SessionAttendances",')
[void]$sb.AppendLine('  "LessonEnrollments",')
[void]$sb.AppendLine('  "LessonSessions",')
[void]$sb.AppendLine('  "LessonTimes",')
[void]$sb.AppendLine('  "Lessons",')
[void]$sb.AppendLine('  "Timeslots"')
[void]$sb.AppendLine('RESTART IDENTITY CASCADE;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('INSERT INTO "Lessons" ("InstructorId","RoomId","Semester","CRN","Name","Type","Department","Code","Credits","TimesPerWeek","Capacity")')
[void]$sb.AppendLine('VALUES')

$values = [System.Collections.Generic.List[string]]::new()
$semSql = Escape-SqlLiteral $Semester
foreach ($r in $rows) {
    $key = Get-PrimaryInstructorKey -Raw $r.instructor
    $iid = $instructorIdByKey[$key]
    $name = Escape-SqlLiteral $r.courseTitle
    $dept = Escape-SqlLiteral $r.subjectDescription
    $code = Escape-SqlLiteral $r.courseNumber
    $crn = Escape-SqlLiteral $r.CRN
    $cap = [int]$r.availableSeats
    $tpw = [int]$r.lessonsPWeek
    $values.Add("($iid, $RoomId, '$semSql', '$crn', '$name', 'Section', '$dept', '$code', $DefaultCredits, $tpw, $cap)")
}

[void]$sb.AppendLine(($values -join ",`n"))
[void]$sb.AppendLine(';')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('COMMIT;')

$sql = $sb.ToString()

if ($WhatIf) {
    Write-Host $sql
    exit 0
}

if ($SqlOnly) {
    $out = if ($OutputSqlPath) { $OutputSqlPath } else { Join-Path $PSScriptRoot 'seed.sql' }
    $sql | Set-Content -LiteralPath $out -Encoding UTF8
    Write-Host "Wrote SQL to $out (database not modified). Run with psql or pipe into Docker."
    exit 0
}

$sqlFile = Join-Path $env:TEMP ("myada_seed_{0}.sql" -f [Guid]::NewGuid().ToString('N'))
$sql | Set-Content -LiteralPath $sqlFile -Encoding UTF8

try {
    if ($ConnectionUrl) {
        $env:PGPASSWORD = if ($Password) { $Password } else { $env:PGPASSWORD }
        & psql $ConnectionUrl -v ON_ERROR_STOP=1 -f $sqlFile
        if ($LASTEXITCODE -ne 0) { throw "psql failed with exit $LASTEXITCODE" }
    }
    else {
        if (-not $Password) {
            throw 'Set -Password or $env:PGPASSWORD when not using -ConnectionUrl'
        }
        $env:PGPASSWORD = $Password
        $conn = "host=$HostName port=$Port dbname=$Database user=$UserName"
        & psql $conn -v ON_ERROR_STOP=1 -f $sqlFile
        if ($LASTEXITCODE -ne 0) { throw "psql failed with exit $LASTEXITCODE" }
    }
}
finally {
    Remove-Item -LiteralPath $sqlFile -ErrorAction SilentlyContinue
}

if ($OutputSqlPath) {
    $sql | Set-Content -LiteralPath $OutputSqlPath -Encoding UTF8
    Write-Host "Also saved SQL copy to $OutputSqlPath"
}

Write-Host "Seed complete. $($rows.Count) lessons inserted. $($instructorIdByKey.Count) distinct instructor keys mapped to InstructorId 1..$($instructorIdByKey.Count)."
